// Static course data — used as fallback when API is unavailable
const COURSES_DATA = [
  {
    id: '1',
    title: 'Modern Crop Management Fundamentals',
    category: 'crop-management',
    level: 'beginner',
    description:
      'Learn the essentials of modern crop management, from seed selection to harvest planning. This course covers soil preparation, planting schedules, irrigation timing, and nutrient management for small to mid-scale farms.',
    rating: 4.8,
    instructor: 'Dr. Anika Perera',
    duration: 12,
    students: 3420,
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&auto=format&fit=crop',
  },
  {
    id: '2',
    title: 'Soil Science & Health Optimization',
    category: 'soil-science',
    level: 'intermediate',
    description:
      'Dive deep into soil biology, chemistry, and physics. Learn how to test, amend, and maintain soil health for maximum productivity. Covers composting, microbial activity, pH balancing, and organic matter management.',
    rating: 4.6,
    instructor: 'Prof. Rajan Nair',
    duration: 16,
    students: 2210,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&auto=format&fit=crop',
  },
  {
    id: '3',
    title: 'Integrated Pest Management (IPM)',
    category: 'pest-control',
    level: 'intermediate',
    description:
      'Master the art of keeping crops safe using Integrated Pest Management techniques. Learn to identify common agricultural pests, use biological controls, apply targeted pesticides, and monitor pest cycles for minimum chemical intervention.',
    rating: 4.7,
    instructor: 'Dr. Suresh Kumara',
    duration: 10,
    students: 1875,
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&auto=format&fit=crop',
  },
  {
    id: '4',
    title: 'Smart Irrigation & Water Management',
    category: 'irrigation',
    level: 'beginner',
    description:
      'Understand water requirements for different crops and design efficient irrigation systems. Topics include drip irrigation, sprinkler systems, rainwater harvesting, soil moisture sensors, and water conservation strategies.',
    rating: 4.5,
    instructor: 'Eng. Malika Fernando',
    duration: 8,
    students: 2640,
    image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&auto=format&fit=crop',
  },
  {
    id: '5',
    title: 'Certified Organic Farming Practices',
    category: 'organic-farming',
    level: 'beginner',
    description:
      'Start your journey into organic farming with this comprehensive certification-prep course. Learn organic certification requirements, natural fertilizers, companion planting, cover cropping, and sustainable land management.',
    rating: 4.9,
    instructor: 'Ms. Priya Shankar',
    duration: 20,
    students: 4100,
    image: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=600&auto=format&fit=crop',
  },
  {
    id: '6',
    title: 'Agri-Business & Farm Profitability',
    category: 'business',
    level: 'advanced',
    description:
      'Turn your farm into a profitable business. This advanced course covers farm financial planning, marketing strategies, value chain development, cooperative management, agri-tourism, and government grant applications.',
    rating: 4.4,
    instructor: 'Mr. Dinesh Weerasinghe',
    duration: 14,
    students: 1550,
    image: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=600&auto=format&fit=crop',
  },
  {
    id: '7',
    title: 'Advanced Crop Disease Diagnosis',
    category: 'crop-management',
    level: 'advanced',
    description:
      'Learn to identify, diagnose, and treat over 50 common crop diseases using visual inspection and digital tools. Understand disease cycles, fungal vs bacterial infections, and develop treatment and prevention protocols.',
    rating: 4.7,
    instructor: 'Dr. Anika Perera',
    duration: 18,
    students: 980,
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&auto=format&fit=crop',
  },
  {
    id: '8',
    title: 'Composting & Natural Fertilizer Production',
    category: 'organic-farming',
    level: 'beginner',
    description:
      'Transform farm waste into black gold! This hands-on course teaches vermicomposting, aerobic composting, liquid fertilizer production (Bokashi, bio-slurry), and how to apply them for different crops.',
    rating: 4.6,
    instructor: 'Ms. Priya Shankar',
    duration: 6,
    students: 3300,
    image: 'https://images.unsplash.com/photo-1598512752271-33f913a5af13?w=600&auto=format&fit=crop',
  },
  {
    id: '9',
    title: 'Precision Agriculture with Technology',
    category: 'crop-management',
    level: 'advanced',
    description:
      'Harness the power of IoT, drones, GPS mapping, and AI-driven analytics for precision farming. Learn to use sensors, satellite imagery, data dashboards, and automated systems to maximize yield and reduce waste.',
    rating: 4.8,
    instructor: 'Dr. Kavinda Jayalath',
    duration: 22,
    students: 760,
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&auto=format&fit=crop',
  },
  {
    id: '10',
    title: 'Soil pH & Nutrient Cycle Mastery',
    category: 'soil-science',
    level: 'advanced',
    description:
      'An in-depth exploration of macro and micronutrient cycles in agricultural soils. Learn soil testing protocols, deficiency symptom identification, fertilizer calculations, and creating custom soil amendment plans.',
    rating: 4.5,
    instructor: 'Prof. Rajan Nair',
    duration: 14,
    students: 1120,
    image: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=600&auto=format&fit=crop',
  },
  {
    id: '11',
    title: 'Biological Pest Control Methods',
    category: 'pest-control',
    level: 'beginner',
    description:
      'Explore eco-friendly pest control using beneficial insects, natural predators, traps, and plant-based repellents. Reduce chemical costs and improve ecological balance on your farm with proven biological techniques.',
    rating: 4.3,
    instructor: 'Dr. Suresh Kumara',
    duration: 7,
    students: 1650,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&auto=format&fit=crop',
  },
  {
    id: '12',
    title: 'Farm-to-Market: Supply Chain Management',
    category: 'business',
    level: 'intermediate',
    description:
      'Learn how to efficiently move your produce from farm to end consumer. Topics include post-harvest handling, cold chain logistics, packaging, pricing strategies, direct-to-consumer channels, and digital marketplace integration.',
    rating: 4.6,
    instructor: 'Mr. Dinesh Weerasinghe',
    duration: 11,
    students: 2080,
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&auto=format&fit=crop',
  },
];

export default COURSES_DATA;
